---
- name: install pm2 globally
  become_user: "{{ project_user }}"
  become: yes
  npm: name=pm2 state=present global=yes
  notify: update pm2

- name: Looking up user home
  shell: >
    egrep "^{{ project_user }}:" /etc/passwd | awk -F: '{ print $6 }'
  changed_when: false
  register: pm2_user_home

- name: Installing startup script
  command: "pm2 startup -u {{ project_user }} --hp {{ pm2_user_home.stdout }}"
