- name: Check if version.txt Exists
  become: yes
  stat:
    path: "{{ install_dir }}/version.txt"
  register: version_file_exists

- name: Check contents of version.txt
  become: yes
  command: cat "{{ install_dir }}/version.txt"
  register: version_file_contents
  when: version_file_exists.stat.exists
  changed_when: false

- name: Print Environment
  debug:
    msg: "{{ env }}"
- import_tasks: deploy.yml
  when: version_file_contents.stdout is undefined or version_file_contents.stdout != packageURL

- import_tasks: install.yml
  tags:
    - web
    - pm2
    - install
    - pm2-install

- import_tasks: manage.yml
  tags:
    - web
    - pm2
    - manage
    - pm2-manage

- import_tasks: service.yml
  tags:
    - web
    - pm2
    - service
    - pm2-service
